// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dns_log.sql

package db

import (
	"context"
)

const createDNSLog = `-- name: CreateDNSLog :one
INSERT INTO dns_log (dns_query_record,
                     type,
                     ip_address,
                     location)
VALUES ($1, $2, $3, $4) RETURNING id, dns_query_record, type, ip_address, location, created_at
`

type CreateDNSLogParams struct {
	DnsQueryRecord string `json:"dns_query_record"`
	Type           string `json:"type"`
	IpAddress      string `json:"ip_address"`
	Location       string `json:"location"`
}

func (q *Queries) CreateDNSLog(ctx context.Context, arg CreateDNSLogParams) (DnsLog, error) {
	row := q.db.QueryRow(ctx, createDNSLog,
		arg.DnsQueryRecord,
		arg.Type,
		arg.IpAddress,
		arg.Location,
	)
	var i DnsLog
	err := row.Scan(
		&i.ID,
		&i.DnsQueryRecord,
		&i.Type,
		&i.IpAddress,
		&i.Location,
		&i.CreatedAt,
	)
	return i, err
}
