// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"time"
)

type DnsLog struct {
	ID             int64     `json:"id"`
	DnsQueryRecord string    `json:"dns_query_record"`
	Type           string    `json:"type"`
	IpAddress      string    `json:"ip_address"`
	Location       string    `json:"location"`
	CreatedAt      time.Time `json:"created_at"`
}
