// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"
)

type Querier interface {
	CreateDNSLog(ctx context.Context, arg CreateDNSLogParams) (DnsLog, error)
}

var _ Querier = (*Queries)(nil)
